<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <DefineConstants>FABLE_COMPILER</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="PowerSync.fs" />
    <Compile Include="Db.fs" />
    <Compile Include="CodeMirror.fs" />
    <Compile Include="CooklangEditor.fs" />
    <Compile Include="App.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Shared/Shared.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fable.Core" Version="5.*" />
    <PackageReference Include="Fable.Browser.Dom" Version="2.*" />
    <PackageReference Include="Fable.Promise" Version="3.*" />
    <PackageReference Include="Fable.Elmish" Version="5.*" />
    <PackageReference Include="Feliz" Version="3.*" />
    <PackageReference Include="Feliz.UseElmish" Version="5.*" />
    <PackageReference Include="Fable.Fetch" Version="2.*" />
    <PackageReference Include="Thoth.Json.JavaScript" Version="0.*" />
  </ItemGroup>
</Project>
